AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple SAM Lambda Function

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for the Lambda function
    Value:
      Fn::Join:
        - ''
        - - 'https://'
          - Fn::Sub: '${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com'
          - '/Prod/hello/'
